# Assignment 1 NumPy



In [ ]:
#Import the libraries 
import numpy as np

# Problem 1 
Matrix Manipulations

Lets first create a matrix and perform some manipulations of it.

Using numpy's matrix data structure, define the following matricies:

$$A=\left[ \begin{array}{ccc} 3 & 5 & 9 \\ 3 & 3 & 4 \\ 5 & 9 & 17 \end{array} \right]$$

$$B=\left[ \begin{array}{c} 2 \\ 1 \\ 4 \end{array} \right]$$

After this solve the matrix equation:
$$Ax = B$$

In [ ]:
A = np.array([[3,5,9],[3,3,4],[5,9,17]])
B = np.array([[2],[1],[4]])
np.linalg.solve(A,B)

array([[ 1.],
       [-2.],
       [ 1.]])

# Problem 2
Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element
Input: $$arrayOne = \left[\begin{array}{ccc} 5& 6& 9\\ 21 & 18 & 27\end{array}\right]$$
       $$arrayTwo = \left[\begin{array}{ccc} 15 &33& 24\\ 4 &7& 1\end{array}\right]$$



In [ ]:
arr1 = np.array([[5,6,9],[21,18,27]])
arr2 = np.array([[15,33,24],[4,7,1]])
np.square(arr1+arr2)

array([[ 400, 1521, 1089],
       [ 625,  625,  784]])

# Problem 3
Print max from axis 0 and min from axis 1 from the following 2-D array.\
$$sampleArray = \left[\begin{array}{ccc} 34&43&73 \\ 82&22&12 \\ 53&94&66 \end{array}\right]$$




In [ ]:
A = np.array([[34,43,73],[82,22,12],[53,94,66]])

Max0 = np.amax(A, 0) 
print("Printing MAX Of Axis 0")
print(Max0)

Min1 = np.amin(A, 1) 
print("Printing MIN Of Axis 1")
print(Min1)


Printing MAX Of Axis 0
[82 94 73]
Printing MIN Of Axis 1
[34 12 53]


# Problem 4
Get the positions where elements of a and b match\
Input:  a = np.array([1,2,3,2,3,4,3,4,5,6])\
b = np.array([7,2,10,2,7,4,9,4,9,8])\
Desired Output: array([1, 3, 5, 7])

In [ ]:
A= input(np.array([]))
B= np.array([7,2,10,2,7,4,9,4,9,8])
np.where(A==B)


# Problem 5
Given 
$$a= \left[\begin{array}{cc} 1&2\\ 3&4 \end{array}\right]$$
$$b = \left[\begin{array}{cc} 5&6 \\ 7&8 \end{array}\right]$$
Obtain c and d
$$c = \left[\begin{array}{cc} 1&2\\ 3&4 \\ 5&6 \\ 7&8 \end{array}\right]$$
$$d = \left[\begin{array}{cccc} 1&2&5&6\\ 3&4&7&8 \end{array}\right]$$

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
c= np.concatenate((A,B))
d= np.concatenate((A,B),axis=1)
print("c=",c)
print("d=",d)

c= [[1 2]
 [3 4]
 [5 6]
 [7 8]]
d= [[1 2 5 6]
 [3 4 7 8]]
